name: 'Dependency review'

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

permissions:
  contents: read
  pull-requests: write

jobs:
  dependency-review:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4

      # Conditionally handle pull requests and pushes
      - name: 'Dependency Review'
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/dependency-review-action@v4
        with:
          comment-summary-in-pr: always

      - name: 'Dependency Snapshot Submission'
        if: ${{ github.event_name == 'push' }}
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: critical # Or adjust as needed
